version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
